name: read content

on:
  push:
    branches: main

jobs:
  read_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: read file
        run: cat hello.txt